import React from 'react';

const ContentScroll = () => {
    return (
        <div className="">
            <div className=" items-center justify-center bg-white  pb-[20px]">
                <div className='p-5 border-[#CACACA] border text-sm rounded-lg  w-fit mx-auto'>
                    <div className=" text-sm   sm:container  h-[485px] overflow-y-auto sm:p-6 custom-scrollbar ">
                        <div className='sm:container'>
                            <p>Please read carefully the Terms &amp; Conditions set out below before booking your journey through XRide Ltd website. You must agree to the CABBX Ltd terms &amp; Conditions before proceeding with your booking by ticking the box ‘I agree to CABBX Terms &amp; Conditions’ when booking your journey. If you do not agree with the Terms &amp; Conditions please do not go ahead and book your journey through CABBX Ltd. By accepting the Terms &amp; Conditions you are agreeing that you have the authority and have the authority for representing the person you are booking on behalf of. You agree that:</p>
                            <ul className="list-disc list-inside my-4">
                                <li>You are at least 18 years old and have the legal capacity to be bound by these Terms &amp; Conditions.</li>
                                <li>Have read and understood the Terms &amp; Conditions.</li>
                            </ul>
                            <h3 className="text-[14px] font-bold text-gray-700 mt-6 mb-2">USE OF WEBSITE</h3>
                            <p>When making a booking through CABBX Ltd website you are responsible for accurately providing the correct details. You will be responsible if you fail to provide accurate details.</p>
                            <p>CABBX Ltd is a price comparison website and acts as an agent for Licensed Taxi, Private Hire Operators (PHO) and  Coach Operators and is not a Licensed Private Hire operator itself.</p>
                            <p>CABBX Ltd does not guarantee that it will be able to meet Your needs, and it reserves the right to reject any bookings you request and to cancel any bookings you have already made. In such a scenario, CABBX Ltd will reimburse the fee you paid to you in full satisfaction of any claims you may have.</p>
                            <p>{"CABBX Ltd will record your details and information about how You use the website, but your personal information  won't be shared with anyone other than the Taxi and Private Hire Operator or used for any other reason than to carry out the services agreed upon, subject to the terms of the CABBX Ltd privacy policy."}</p>
                            <p>When you visit the website, CABBX Ltd can transfer a small file to your computer. This &quot;cookie&quot; will provide CABBX Ltd the ability to monitor how you use the website and pinpoint specific areas of interest to improve Your subsequent visits. CABBX Ltd will not be able to identify you through the cookie, and CABBX Ltd will only use it in connection with this website. You can configure your web browser to refuse cookies, but doing so might make it impossible to access some features of our website. If required to do so by law, or at the request of a law enforcement agency or governmental body, CABBX Ltd may share Your Personal Data.</p>
                            <p>Send an email to info@x-ride.co.uk with the subject line &quot;unsubscribe&quot; if you do not want CABBX Ltd to use your email address to send you information on anything other than your booking.</p>
                            <h3 className="text-[14px] font-bold text-gray-700 mt-6 mb-2">BOOKINGS</h3>
                            <p>{"When you enter the trip's specifics, CABBX Ltd will make an effort to get you quotes over the website from one or more private hire and/or taxi operators who can meet your needs. The Quotes are the current unique &quot;one-time&quot;  special offers from Private Hire Operators that are only accessible at the time that Your Booking is made."}</p>
                            <p>You are in charge of checking that your Information is accurate. When you make a Booking, you are making CABBX Ltd an offer, which it may accept or reject. Until you see the confirmation on the website and or confirmation email, your reservation is not confirmed.</p>
                            <p>The Private Hire Operator Terms &amp; Conditions may also apply to any Booking You make; but, in the event of a discrepancy between the Private Hire Operators Terms &amp; Conditions and the contents of this agreement, the provisions of this agreement will take precedence.</p>
                            <p>It is the Private Hire Operators responsibility to enforce their Terms &amp; Conditions on you if it so chooses. In the event that you have any particular requirements you should not use this website and should instead make alternative travel arrangements that address your particular requirements, as CABBX Ltd cannot certify the ability of the Private Hire Operators to fulfil any particular requirements. You should always check directly with the Private Hire Operator for any particular requirement.</p>
                            <p>CABBX Ltd maintains the right to correct any typographical errors, including pricing errors, in any aspects of the material that appears on the Website. If, after being made aware of the error, you decide you do not want to move forward with the purchase, you are free to withdraw your offer, and any money you have already paid will be fully reimbursed.</p>
                            <p>You understand and agree that CABBX Ltd is the Private Hire Operator’s agent and that, notwithstanding its best efforts to address any complaints you may have regarding the Private Hire Operator’s services, you must pursue any legal remedies against the Private Hire Operator and not CABBX Ltd.</p>
                            <p>For reservations that are to be made in advance using a credit card, CABBX Ltd has the right to obtain payment from you acting solely in its own right for the booked trip and settle all associated card costs before making the payment due to the Private Hire Operator as the Private Hire Operator’s booking agent. You acknowledge that in order to ensure the fulfilment of the booking made through this Website, Private Hire Operator’s hereby grant CABBX Ltd the right to novate the contract between you and the Private Hire Operator for the provision of transportation services where the Private Hire Operator deems it appropriate. CABBX Ltd website Allows you to make a booking(s) with the Private Hire Operator you choose. Your preferred transport company will get in touch with you after your reservation is confirmed to set up the Pick-up Departure Time and Meeting Location. A few hours prior to your pick-up departure time, the transport company may get in touch with you. We advise you to get in touch with your transport provider in advance to confirm the Pick-up Departure Time and Meeting Location in order to avoid last-minute issues.</p>
                            <p>{"When making a booking, please note that CABBX ltd will not be responsible for any delays or costs incurred by the booker arising through the Private Hire Operators driver turning up late and should be claimed directly from the Private Hire Operator. When making a booking, it is your responsibility to ensure that you allow sufficient travelling time, especially when travelling to the airport or train stations. CABBX Ltd will not be liable for any delays arising out of traffic delays, accidents enroute, roadworks or any other mishap and or delays by the Private Hire Operator. CABBX Ltd does not accept any responsibility in any way for missed flights, for whatever reason i.e. traffic delays, accidents, breakdowns, severe weather conditions or any unforeseen circumstances. Should you miss your flight then you will have to contact the Private Hire Operator carrying out your journey to see what their Terms & Conditions state. If you or your party's Conduct or Behaviour Is Disruptive in any way and/or affects your safety or that of the driver of the vehicle, the Private Hire Operator reserves the right to terminate the trip in its reasonable judgement. CABBX Ltd and the Private Hire Operator disclaim all responsibility for any additional expenses you or your party may incur as a result of the Private Hire Operator acting in this manner. Alcoholic beverages cannot be brought into the cars by passengers to be consumed while on the trip. Private Hire Operators additionally retain the right to refuse service to anyone who is deemed to be intoxicated or under the influence of drugs or alcohol."}</p>
                            <h3 className="text-[14px] font-bold text-gray-700 mt-6 mb-2">PRICE &amp; PAYMENT</h3>
                            <p>All prices listed on our website are based on the details you provide. If there is a change in the precise details, there will be a variation in the quoted rates.</p>
                            <p>The Private Hire Operators may offer extra services to the ones you requested during the booking process and charge additional costs that may not be included in the price given through this website. You must pay the Private Hire Operators directly for these extra services. Child safety seats are not included in the cost of your reservation.</p>
                            <p>For the provision of these services, the Private Hire Operators may impose an additional fee. Child seats must be requested at the time of booking as they are subject to availability. Please make sure you have your own child seats if the Private Hire Operators are unable to do so. At the time of booking, the cost of any telephone bookings will be communicated.</p>
                            <p>In the case of online reservations, it is your responsibility to print out the confirmation emails for the reservation, which include the trip specifics as well as the contact information for CABBX Ltd and the Private Hire Operator. It is your duty to verify that all of the information is accurate and to inform CABBX Ltd right away if any of it is wrong. Any errors that are not promptly corrected or that are not reported within the timeframes specified in the confirmation email will not be the responsibility of CABBX Ltd.</p>
                            <h3 className="text-[14px] font-bold text-gray-700 mt-6 mb-2">CANCELLATION &amp; REFUNDS</h3>
                            <p>Cancellations of a pre-booked reservation must be done directly with CABBX Ltd by the Booker at least 24 hours prior to the pick-up departure time. In the case of cancellations less than 24 hours prior to the pickup departure time or in case of a “no show,” there will be no refund of any payment. For airport pickups, CABBX Ltd provides 60 minutes of free waiting time for inbound (arrival) journeys, starting from the flight landing time, after which you will be charged for waiting time according to the relevant Private Hire Operators rates and policy.</p>
                            <h3 className="text-[14px] font-bold text-gray-700 mt-6 mb-2">PRIVACY</h3>
                            <p>We take your privacy very seriously and will only use your personal information in accordance with our Privacy Policy. By using our website, you consent to our collection and use of your personal information as described in our Privacy Policy.</p>
                            <h3 className="text-[14px] font-bold text-gray-700 mt-6 mb-2">LIMITATION OF LIABILITY</h3>
                            <p>{"CABBX Ltd and its affiliates, agents, and licensors shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the website or services. In no event will CABBX Ltd's liability to you exceed the amount paid by you for the services in question."}</p>
                            <h3 className="text-[14px] font-bold text-gray-700 mt-6 mb-2">GOVERNING LAW</h3>
                            <p>These Terms &amp; Conditions shall be governed by and construed in accordance with the laws of England and Wales. Any disputes arising out of or in connection with these Terms &amp; Conditions shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
                        </div>
                    </div>
                </div>

                <div className="sm:w-[85%] mx-auto">

                    <div className='w-[90%] mx-auto h-5 rounded-b-[10px]  bg-[#193D1C] sm:w-[85%]'>

                    </div>
                </div>

            </div>

        </div>
    );
};

export default ContentScroll;
